#include <stdio.h>
#include <time.h>

int main()
{
    time_t current_time;
    char time_string[100];
    struct tm *time_info;

    // get 
    time(&current_time);
    // convert
    time_info = localtime(&current_time);

    // format
    strftime(time_string, sizeof(time_string), "%Y-%m-%d %H:%M:%S", time_info);


    // CGI: 自己打印HTTP头部, 并以空行结束头部
    printf("Content-Type: text/html\n\n");

    
    // HTTP 内容
    printf("<html>\n");
    printf("<head><title>CGI Time</title></head>\n");
    printf("<body>\n");
    printf("<h1>Current Server Time</h1>\n");
    printf("<p>The current date and time on the server is: <strong>%s</strong></p>\n", time_string);
    printf("<p>This page was dynamically generated by a CGI program.</p>\n");
    printf("</body>\n");
    printf("</html>\n");

    return 0;
}